#!/bin/bash

# Checkout a copy of the Git repository for the Kafka operator. This is to
# make it easier to deploy the Kafka operator into the cluster initially. See
# installation steps in 'workshop/exercises/00-installing-the-operator.md'.

git clone https://github.com/strimzi/strimzi-kafka-operator.git
