#!/bin/bash

# Checkout a copy of the Git repository for the Kafka operator. We need to
# do this so we have copies of rolebinding resource definitions to be added
# to each project. Also used during initial setup by the cluster admin.

git clone https://github.com/strimzi/strimzi-kafka-operator.git
