apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-session-rules
parameters:
- name: JUPYTERHUB_NAMESPACE
  value: ""
  required: true
- name: JUPYTERHUB_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    labels:
      app: ${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}
    name: ${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}-session-rules
  rules:
  - apiGroups:
    - "kafka.strimzi.io"
    resources:
    - kafkas
    - kafkaconnects
    - kafkaconnects2is
    - kafkamirrormakers
    - kafkausers
    - kafkatopics
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
